/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package com.ipc2ss.cardmanager.frontend;

import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author brigidoalvarado
 */
public class CardManagerApp extends javax.swing.JFrame {

    /**
     * Creates new form CardManaerApp
     */
    private String entryPath;
    private String exitPath;
    
    public CardManagerApp() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entriesFilejDsktpPn = new javax.swing.JDesktopPane();
        chooseFolderButton = new javax.swing.JButton();
        chooseTxtButton = new javax.swing.JButton();
        speedsComboBox = new javax.swing.JComboBox<>();
        chargejButton = new javax.swing.JButton();
        chooserTextjPnl = new javax.swing.JPanel();
        EnterTextJLbl = new javax.swing.JLabel();
        fileChooserjPnl = new javax.swing.JPanel();
        endFolderJLbl1 = new javax.swing.JLabel();
        logtexjPnl = new javax.swing.JPanel();
        logTextJLb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArchivojMn = new javax.swing.JMenu();
        NuevaCargajMnItm = new javax.swing.JMenuItem();
        OperacionejMn = new javax.swing.JMenu();
        MovimientosjMnItm = new javax.swing.JMenuItem();
        AutorizarjMnItm = new javax.swing.JMenuItem();
        CancelarjMnItm = new javax.swing.JMenuItem();
        ConsultasjMn = new javax.swing.JMenu();
        consultarTarjetajMnItm = new javax.swing.JMenuItem();
        estadoCuentajMnItm = new javax.swing.JMenuItem();
        listadoSolicitudesjMnItm = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });

        entriesFilejDsktpPn.setBackground(new java.awt.Color(51, 51, 51));
        entriesFilejDsktpPn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        entriesFilejDsktpPn.setForeground(new java.awt.Color(153, 153, 153));
        entriesFilejDsktpPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chooseFolderButton.setText("...");
        chooseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFolderButtonActionPerformed(evt);
            }
        });
        entriesFilejDsktpPn.add(chooseFolderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 66, -1));

        chooseTxtButton.setText("...");
        chooseTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTxtButtonActionPerformed(evt);
            }
        });
        entriesFilejDsktpPn.add(chooseTxtButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 67, 66, 29));

        speedsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        speedsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedsComboBoxActionPerformed(evt);
            }
        });
        entriesFilejDsktpPn.add(speedsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 170, 78, -1));

        chargejButton.setText("cargar");
        chargejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargejButtonActionPerformed(evt);
            }
        });
        entriesFilejDsktpPn.add(chargejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 171, 76, -1));

        chooserTextjPnl.setBackground(new java.awt.Color(255, 255, 255));
        chooserTextjPnl.setForeground(new java.awt.Color(255, 255, 255));

        EnterTextJLbl.setBackground(new java.awt.Color(255, 255, 255));
        EnterTextJLbl.setForeground(new java.awt.Color(0, 0, 0));
        EnterTextJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnterTextJLbl.setText("Seleccionar Archivo de Entrada");
        EnterTextJLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        javax.swing.GroupLayout chooserTextjPnlLayout = new javax.swing.GroupLayout(chooserTextjPnl);
        chooserTextjPnl.setLayout(chooserTextjPnlLayout);
        chooserTextjPnlLayout.setHorizontalGroup(
            chooserTextjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnterTextJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        chooserTextjPnlLayout.setVerticalGroup(
            chooserTextjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserTextjPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EnterTextJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        entriesFilejDsktpPn.add(chooserTextjPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 67, -1, -1));

        fileChooserjPnl.setBackground(new java.awt.Color(255, 255, 255));
        fileChooserjPnl.setForeground(new java.awt.Color(255, 255, 255));

        endFolderJLbl1.setBackground(new java.awt.Color(255, 255, 255));
        endFolderJLbl1.setForeground(new java.awt.Color(0, 0, 0));
        endFolderJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endFolderJLbl1.setText("Seleccionar Carpeta de Salida");

        javax.swing.GroupLayout fileChooserjPnlLayout = new javax.swing.GroupLayout(fileChooserjPnl);
        fileChooserjPnl.setLayout(fileChooserjPnlLayout);
        fileChooserjPnlLayout.setHorizontalGroup(
            fileChooserjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileChooserjPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endFolderJLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        fileChooserjPnlLayout.setVerticalGroup(
            fileChooserjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileChooserjPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(endFolderJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        entriesFilejDsktpPn.add(fileChooserjPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 123, -1, -1));

        logtexjPnl.setBackground(new java.awt.Color(255, 255, 255));
        logtexjPnl.setForeground(new java.awt.Color(255, 255, 255));

        logTextJLb.setBackground(new java.awt.Color(255, 255, 255));
        logTextJLb.setForeground(new java.awt.Color(0, 0, 0));
        logTextJLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logTextJLb.setText("...");

        javax.swing.GroupLayout logtexjPnlLayout = new javax.swing.GroupLayout(logtexjPnl);
        logtexjPnl.setLayout(logtexjPnlLayout);
        logtexjPnlLayout.setHorizontalGroup(
            logtexjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logTextJLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        logtexjPnlLayout.setVerticalGroup(
            logtexjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logtexjPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logTextJLb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        entriesFilejDsktpPn.add(logtexjPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 8, -1, -1));

        ArchivojMn.setText("Archivo");

        NuevaCargajMnItm.setText("Nueva Carga");
        NuevaCargajMnItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCargajMnItmActionPerformed(evt);
            }
        });
        ArchivojMn.add(NuevaCargajMnItm);

        jMenuBar1.add(ArchivojMn);

        OperacionejMn.setText("Operaciones");

        MovimientosjMnItm.setText("Movimiento");
        MovimientosjMnItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosjMnItmActionPerformed(evt);
            }
        });
        OperacionejMn.add(MovimientosjMnItm);

        AutorizarjMnItm.setText("Autorizar");
        OperacionejMn.add(AutorizarjMnItm);

        CancelarjMnItm.setText("Cancelar");
        OperacionejMn.add(CancelarjMnItm);

        jMenuBar1.add(OperacionejMn);

        ConsultasjMn.setText("Consultas");

        consultarTarjetajMnItm.setText("ConsultarTarjetajMnItm");
        ConsultasjMn.add(consultarTarjetajMnItm);

        estadoCuentajMnItm.setText("Estado de cuenta");
        ConsultasjMn.add(estadoCuentajMnItm);

        listadoSolicitudesjMnItm.setText("Listado de Solicitudes");
        ConsultasjMn.add(listadoSolicitudesjMnItm);

        jMenuItem1.setText("Listado de Tarjetas");
        ConsultasjMn.add(jMenuItem1);

        jMenuBar1.add(ConsultasjMn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(entriesFilejDsktpPn, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(entriesFilejDsktpPn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formHierarchyChanged

    private void chooseTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTxtButtonActionPerformed
    JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.TXT", "txt");
        jFileChooser.setFileFilter(filter);
        int selection = jFileChooser.showOpenDialog(this);
        
        if (selection == JFileChooser.APPROVE_OPTION) {
            entryPath = jFileChooser.getSelectedFile().getAbsolutePath();
             EnterTextJLbl.setText(jFileChooser.getSelectedFile().getName());
        }
    }//GEN-LAST:event_chooseTxtButtonActionPerformed

    private void chooseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFolderButtonActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selection = jFileChooser.showOpenDialog(this);
       
        if (selection == JFileChooser.APPROVE_OPTION ) {
            exitPath = jFileChooser.getSelectedFile().getAbsolutePath();
            endFolderJLbl1.setText(jFileChooser.getSelectedFile().getName());
        }
    }//GEN-LAST:event_chooseFolderButtonActionPerformed

    private void chargejButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

        if (entryPath == null  &&  exitPath == null) {
             JOptionPane.showMessageDialog(this, "Seleccione un archivo de texto y una carpeta para poder continuar por favor", " ARCHIVOS FALTANTES", JOptionPane.INFORMATION_MESSAGE);

        } else if (entryPath == null) {
                       JOptionPane.showMessageDialog(this, "Seleccione un archivo de texto para cargar sus respectivas solicitudes por favor", " ARCHIVO DE TEXTO FALTANTE", JOptionPane.INFORMATION_MESSAGE);

        } else if (exitPath  == null){
                       JOptionPane.showMessageDialog(this, "Seleccione una carpeta paraa cargar sus posibles reportes", " CARPETA DE SALIDA FALTANTE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            chooseFolderButton.setVisible(false);
            chooseTxtButton.setVisible(false);
            speedsComboBox.setVisible(false);
            chargejButton.setVisible(false);
        }
    }           
    // event_chargejButtonActionPerformed

    private void speedsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedsComboBoxActionPerformed

    private void NuevaCargajMnItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCargajMnItmActionPerformed
        // TODO add your handling code here:
        entryPath = null;
        exitPath = null;
        entriesFilejDsktpPn.setVisible(true);
        logTextJLb.setText("...");
        chooseFolderButton.setVisible(true);
        chooseTxtButton.setVisible(true);
        speedsComboBox.setVisible(true);
        chargejButton.setVisible(true);
        endFolderJLbl1.setText("Seleccionar Archivo de Entrada");
        EnterTextJLbl.setText("Seleccionar Carpeta de Salida");
        speedsComboBox.setSelectedIndex(0);
        
    }//GEN-LAST:event_NuevaCargajMnItmActionPerformed

    private void MovimientosjMnItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosjMnItmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovimientosjMnItmActionPerformed

    private void readerTxt(){
        
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArchivojMn;
    private javax.swing.JMenuItem AutorizarjMnItm;
    private javax.swing.JMenuItem CancelarjMnItm;
    private javax.swing.JMenu ConsultasjMn;
    private javax.swing.JLabel EnterTextJLbl;
    private javax.swing.JMenuItem MovimientosjMnItm;
    private javax.swing.JMenuItem NuevaCargajMnItm;
    private javax.swing.JMenu OperacionejMn;
    private javax.swing.JButton chargejButton;
    private javax.swing.JButton chooseFolderButton;
    private javax.swing.JButton chooseTxtButton;
    private javax.swing.JPanel chooserTextjPnl;
    private javax.swing.JMenuItem consultarTarjetajMnItm;
    private javax.swing.JLabel endFolderJLbl1;
    private javax.swing.JDesktopPane entriesFilejDsktpPn;
    private javax.swing.JMenuItem estadoCuentajMnItm;
    private javax.swing.JPanel fileChooserjPnl;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listadoSolicitudesjMnItm;
    private javax.swing.JLabel logTextJLb;
    private javax.swing.JPanel logtexjPnl;
    private javax.swing.JComboBox<String> speedsComboBox;
    // End of variables declaration//GEN-END:variables

}
